# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
  merge_group:


jobs:
  manual-gate:
    runs-on: ubuntu-latest
    steps:
      - name: Check for ready-to-merge label
        if: github.event_name == 'pull_request' || github.event_name == 'merge_group'
        run: |
          if [[ "${{ github.event.pull_request.labels.*.name }}" != *"ready-to-merge"* ]]; then
            echo "PR not manually approved."
            exit 1
          fi
        # If label is present, job succeeds and merge queue proceeds
